[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_FOURTHWALL_TOKEN = ""
  NEXT_PUBLIC_FOURTHWALL_API = "https://storefront-api.fourthwall.com/v1"
  NEXT_PUBLIC_CHECKOUT_DOMAIN = "deltav-shop.fourthwall.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
